/// <reference types="vite/client" />
import { createClient } from '@supabase/supabase-js';
import { UniversityTrackItem } from '../data/scholarshipTracksData';

// Read Supabase environment variables
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || '';
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

export const isSupabaseConfigured = (): boolean => {
  return Boolean(
    supabaseUrl &&
    supabaseAnonKey &&
    supabaseUrl !== 'https://placeholder.supabase.co' &&
    !supabaseUrl.includes('placeholder')
  );
};

export const supabase = isSupabaseConfigured()
  ? createClient(supabaseUrl, supabaseAnonKey)
  : null;

/**
 * Maps a raw Supabase database row (snake_case or camelCase) to a UniversityTrackItem
 */
export function mapRowToUniversity(row: any, index: number): UniversityTrackItem {
  const uniName = row.university_name || row.universityName || row.name || `University ${index + 1}`;
  const firstLetter = uniName.charAt(0).toUpperCase();

  return {
    id: String(row.id || `supa-${index + 1}`),
    universityName: uniName,
    location: row.location || row.city || row.country || 'Global Campus',
    country: row.country || 'International',
    flag: row.flag || '🏛️',
    foundingYear: row.founding_year || row.foundingYear || '1800',
    scholarshipTitle: row.scholarship_title || row.scholarshipTitle || row.title || 'Institutional Aid',
    ranking: row.ranking || '#1 Tier',
    coverage: row.coverage || (row.has_full_ride ? 'Full Ride' : 'Partial Aid'),
    amountValue: row.amount_value || row.amountValue || row.amount || 'Financial Assistance Available',
    tuitionFee: row.tuition_fee || row.tuitionFee || row.tuition || 'Contact Admissions',
    tuitionAmountNumeric: Number(row.tuition_numeric || row.tuitionAmountNumeric || 0),
    hasFullRide: Boolean(row.has_full_ride ?? row.hasFullRide ?? (row.coverage === 'Full Ride')),
    hasPartialAid: Boolean(row.has_partial_aid ?? row.hasPartialAid ?? true),
    hasFinancialAid: Boolean(row.has_financial_aid ?? row.hasFinancialAid ?? true),
    financialAidType: row.financial_aid_type || row.financialAidType || 'Need-Based',
    minGpa: row.min_gpa || row.minGpa || '3.5 / 4.0',
    minSat: row.min_sat || row.minSat || 'Optional',
    satRequirementCategory: row.sat_category || row.satRequirementCategory || 'Optional',
    minIelts: row.min_ielts || row.minIelts || '6.5+',
    ieltsCategory: row.ielts_category || row.ieltsCategory || '6.5',
    acceptanceRate: row.acceptance_rate || row.acceptanceRate || row.acceptance || '10%',
    deadline: row.deadline || 'Jan 15',
    description: row.description || row.overview || `${uniName} provides premier education and global academic opportunities.`,
    degreesOffered: Array.isArray(row.degrees_offered)
      ? row.degrees_offered
      : Array.isArray(row.degreesOffered)
      ? row.degreesOffered
      : ['Undergraduate', 'Graduate'],
    tags: Array.isArray(row.tags) ? row.tags : ['Global', 'University'],
    requiresSeparateApp: Boolean(row.requires_separate_app ?? row.requiresSeparateApp ?? false),
    logoText: row.logo_text || row.logoText || uniName.split(' ')[0].toUpperCase(),
    logoBg: row.logo_bg || row.logoBg || 'bg-slate-900 text-white',
    supabaseDbId: row.id
  };
}

/**
 * Helper to fetch University Track records from Supabase
 * Queries 'university_scholarships' table or 'universities' table
 */
export async function fetchUniversityScholarshipsFromSupabase() {
  if (!isSupabaseConfigured() || !supabase) {
    return { data: null, error: new Error('Supabase environment variables not configured') };
  }

  try {
    // Try primary table 'university_scholarships'
    let { data, error } = await supabase
      .from('university_scholarships')
      .select('*')
      .limit(300);

    // Fallback to 'universities' if first table doesn't exist or is empty
    if (error || !data || data.length === 0) {
      const res = await supabase.from('universities').select('*').limit(300);
      if (!res.error && res.data && res.data.length > 0) {
        data = res.data;
        error = null;
      }
    }

    if (error) {
      return { data: null, error };
    }

    const formattedList: UniversityTrackItem[] = (data || []).map((row, idx) => mapRowToUniversity(row, idx));
    return { data: formattedList, error: null };
  } catch (err: any) {
    return { data: null, error: err };
  }
}

export const SUPABASE_SQL_SCHEMA = `
-- Execute this script in your Supabase SQL Editor to create the universities table
CREATE TABLE IF NOT EXISTS university_scholarships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  university_name TEXT NOT NULL,
  location TEXT,
  country TEXT,
  flag TEXT DEFAULT '🏛️',
  scholarship_title TEXT,
  ranking TEXT DEFAULT '#1',
  coverage TEXT DEFAULT 'Full Ride',
  amount_value TEXT,
  tuition_fee TEXT,
  tuition_numeric NUMERIC DEFAULT 0,
  has_full_ride BOOLEAN DEFAULT true,
  has_partial_aid BOOLEAN DEFAULT true,
  has_financial_aid BOOLEAN DEFAULT true,
  financial_aid_type TEXT DEFAULT 'Need-Blind',
  min_gpa TEXT DEFAULT '3.5 / 4.0',
  min_sat TEXT DEFAULT '1400+',
  sat_category TEXT DEFAULT '1400',
  min_ielts TEXT DEFAULT '7.0+',
  ielts_category TEXT DEFAULT '7.0',
  acceptance_rate TEXT DEFAULT '5.0%',
  deadline TEXT DEFAULT 'Jan 15',
  description TEXT,
  degrees_offered TEXT[] DEFAULT ARRAY['Undergraduate', 'Graduate'],
  tags TEXT[] DEFAULT ARRAY['Global', 'Scholarship'],
  logo_text TEXT,
  logo_bg TEXT DEFAULT 'bg-indigo-950 text-white',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Read access for public anonymous users
ALTER TABLE university_scholarships ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Read Access" ON university_scholarships FOR SELECT USING (true);
`;
