import { ReadingQuestion } from '../readingTypes';

export const T2_EXERCISES_PART2: ReadingQuestion[] = [
  {
    id: 't2-ex-26',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Easy/Medium Module',
    passage: `In marine zoology, pistol shrimp are renowned for their specialized asymmetrical claws, which can snap shut at velocities exceeding 60 miles per hour. This rapid closure generates a high-speed water jet that creates a cavitation bubble; when the bubble collapses, it produces an acoustic shockwave reaching 210 decibels and temperatures near 4,700°C, instantly stunning small fish and crabs.`,
    questionText: `According to the text, what creates the acoustic shockwave that stuns pistol shrimp prey?`,
    options: [
      'The collapse of a high-speed cavitation bubble generated by claw closure.',
      'Direct physical contact between the shrimp\'s claw and the prey\'s shell.',
      'Sonic vibrations produced by the shrimp\'s tail snapping against rocks.',
      'An electrical impulse discharged from specialized nerve tissue.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Direct Fact Retrieval',
    explanation: {
      passageDeconstruction: `Direct question: What creates the shockwave? Text states: "rapid closure generates a high-speed water jet that creates a cavitation bubble; when the bubble collapses, it produces an acoustic shockwave".`,
      correctReasoning: `Option A accurately states the exact cause given in the text.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'The collapse of a high-speed cavitation bubble...', trapType: 'Direct Textual Match', whyIncorrect: 'Correct. Directly stated in text.' },
        { optionIndex: 1, optionText: 'Direct physical contact between the claw and shell...', trapType: 'Direct Contradiction', whyIncorrect: 'Text states the shockwave from the collapsing water bubble stuns prey at a distance.' },
        { optionIndex: 2, optionText: 'Sonic vibrations produced by tail snapping...', trapType: 'Anatomy Swap Trap', whyIncorrect: 'Claws generate the jet, not tails.' },
        { optionIndex: 3, optionText: 'An electrical impulse discharged from nerve tissue...', trapType: 'Electric Eel Swap Trap', whyIncorrect: 'Pistol shrimp use cavitation bubbles, not electric discharges.' }
      ]
    }
  },
  {
    id: 't2-ex-27',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Hard Module',
    passage: `Although early twentieth-century historians portrayed the Silk Road as a continuous highway traveled by solitary merchants traversing the entirety of Eurasia, modern economic historians emphasize that long-distance trade functioned primarily through a relay system. Commodities like silk, spices, and glass passed through a chain of regional middlemen and oasis trading centers, with few individual traders ever venturing beyond their local geographical zones.`,
    questionText: `Which choice best states the main idea of the passage?`,
    options: [
      'The Silk Road operated as a relay network of regional traders rather than a single direct route traveled by individual merchants.',
      'Silk was the only valuable commodity transported across Eurasian trade networks prior to the fifteenth century.',
      'Eurasian oasis trading centers were completely independent of regional political rulers.',
      'Individual merchants regularly traveled the entire distance between China and Western Europe.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Main Idea Synthesis',
    explanation: {
      passageDeconstruction: `Contrast: early view (single continuous highway, individual long-distance merchants) vs modern view (relay system of regional middlemen and oasis centers).`,
      correctReasoning: `Option A accurately captures the modern historical thesis presented in the text.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'The Silk Road operated as a relay network...', trapType: 'Correct Main Idea', whyIncorrect: 'Correctly contrasts relay network with old single-merchant myth.' },
        { optionIndex: 1, optionText: 'Silk was the only valuable commodity transported...', trapType: 'Unsupported Absolute', whyIncorrect: 'Text mentions silk, spices, and glass, not silk alone.' },
        { optionIndex: 2, optionText: 'Eurasian oasis trading centers were completely independent...', trapType: 'Unmentioned Governance', whyIncorrect: 'Political independence of oasis centers is not discussed.' },
        { optionIndex: 3, optionText: 'Individual merchants regularly traveled the entire distance...', trapType: 'Direct Contradiction', whyIncorrect: 'Text explicitly states "few individual traders ever venturing beyond their local geographical zones".' }
      ]
    }
  },
  {
    id: 't2-ex-28',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Easy/Medium Module',
    passage: `In urban ecology, urban heat islands occur when cities replace natural vegetation with dark asphalt roads and concrete buildings, which absorb solar radiation during the day and re-emit it as thermal heat at night. Environmental planners have found that expanding urban tree canopies and installing reflective cool roofs can reduce localized ambient air temperatures by 2°C to 5°C during summer heatwaves.`,
    questionText: `According to the text, why do cities experience elevated night temperatures?`,
    options: [
      'Dark surfaces absorb solar radiation during the day and re-emit thermal heat at night.',
      'Urban tree canopies trap industrial smog close to ground level.',
      'Cool roofs reflect heat downward into pedestrian thoroughfares.',
      'Concrete buildings generate internal friction heat from elevator operation.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Direct Cause Verification',
    explanation: {
      passageDeconstruction: `Direct detail: Why do cities stay hot at night? Text explicitly states: "dark asphalt roads and concrete buildings... absorb solar radiation during the day and re-emit it as thermal heat at night".`,
      correctReasoning: `Option A directly states the solar radiation absorption and re-emission cause given in the text.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'Dark surfaces absorb solar radiation during the day...', trapType: 'Direct Textual Match', whyIncorrect: 'Correct. Directly stated in text.' },
        { optionIndex: 1, optionText: 'Urban tree canopies trap industrial smog...', trapType: 'Unmentioned Cause', whyIncorrect: 'Trees reduce heat, not trap smog.' },
        { optionIndex: 2, optionText: 'Cool roofs reflect heat downward...', trapType: 'Direct Contradiction', whyIncorrect: 'Cool roofs reflect heat away upward to cool cities.' },
        { optionIndex: 3, optionText: 'Concrete buildings generate internal friction heat...', trapType: 'Fabricated Cause', whyIncorrect: 'Elevator friction is not mentioned.' }
      ]
    }
  },
  {
    id: 't2-ex-29',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Hard Module',
    passage: `While mid-twentieth-century sociologists posited that television viewing would universally erode civic engagement and community cohesion, recent communications research offers a more segmented perspective. Scholars found that while passive consumption of entertainment programming correlates with decreased civic participation, active viewing of local news and public affairs broadcasts actually increases community volunteerism and voter turnout.`,
    questionText: `Which choice best states the main idea of the passage?`,
    options: [
      'The effect of television on civic engagement depends on programming type rather than being universally negative.',
      'Local news broadcasts cause viewers to abandon traditional community organizations.',
      'Passive entertainment programming is more effective at promoting voter turnout than public affairs broadcasts are.',
      'Sociologists in the mid-twentieth century accurately predicted the impact of modern digital media.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Main Idea Synthesis',
    explanation: {
      passageDeconstruction: `Contrast: old theory (TV universally erodes civic life) vs modern finding (passive entertainment decreases participation, BUT local news increases volunteerism/voting).`,
      correctReasoning: `Option A accurately synthesizes that TV\'s impact depends on programming type.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'The effect of television on civic engagement depends on...', trapType: 'Correct Main Idea', whyIncorrect: 'Correctly summarizes the segmented perspective.' },
        { optionIndex: 1, optionText: 'Local news broadcasts cause viewers to abandon community...', trapType: 'Direct Contradiction', whyIncorrect: 'Text states local news increases volunteerism.' },
        { optionIndex: 2, optionText: 'Passive entertainment programming is more effective...', trapType: 'Direct Contradiction', whyIncorrect: 'Text states passive viewing correlates with decreased participation.' },
        { optionIndex: 3, optionText: 'Sociologists in the mid-twentieth century accurately predicted...', trapType: 'Direct Contradiction', whyIncorrect: 'Text shows early sociologists\' universal negative prediction was incomplete.' }
      ]
    }
  },
  {
    id: 't2-ex-30',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Easy/Medium Module',
    passage: `In cognitive neuroscience, working memory capacity refers to the limited system responsible for temporarily holding and manipulating information during complex reasoning tasks. Functional MRI scans demonstrate that working memory relies primarily on the dorsolateral prefrontal cortex, which maintains neural firing patterns even when sensory stimuli are removed from view.`,
    questionText: `According to the text, which brain region is primarily responsible for working memory?`,
    options: [
      'The dorsolateral prefrontal cortex.',
      'The occipital visual cortex.',
      'The primary motor cortex.',
      'The brainstem auditory pathway.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Direct Anatomical Retrieval',
    explanation: {
      passageDeconstruction: `Direct question: Which brain region governs working memory? Text explicitly identifies "the dorsolateral prefrontal cortex".`,
      correctReasoning: `Option A directly names the exact brain region stated in the passage.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'The dorsolateral prefrontal cortex.', trapType: 'Direct Textual Match', whyIncorrect: 'Correct. Directly stated in text.' },
        { optionIndex: 1, optionText: 'The occipital visual cortex.', trapType: 'Unmentioned Anatomical Region', whyIncorrect: 'Occipital cortex is not mentioned.' },
        { optionIndex: 2, optionText: 'The primary motor cortex.', trapType: 'Unmentioned Anatomical Region', whyIncorrect: 'Motor cortex is not mentioned.' },
        { optionIndex: 3, optionText: 'The brainstem auditory pathway.', trapType: 'Unmentioned Anatomical Region', whyIncorrect: 'Brainstem auditory pathway is not mentioned.' }
      ]
    }
  },
  {
    id: 't2-ex-31',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Hard Module',
    passage: `While traditional musicology attributed the origin of New Orleans jazz solely to West African rhythmic traditions, contemporary music historians recognize it as a complex synthesis. African syncopation and call-and-response structures blended with European harmonic progressions, French quadrille dance forms, and Spanish Caribbean habanera rhythms, creating a uniquely hybrid musical form in the cosmopolitan port city.`,
    questionText: `Which choice best states the main idea of the text?`,
    options: [
      'New Orleans jazz emerged from a blend of West African, European, and Caribbean musical influences.',
      'West African rhythmic traditions were completely excluded from early jazz compositions.',
      'French quadrille dance music was the single most important contributor to jazz harmony.',
      'European harmonic progressions developed independently of global trade routes.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Synthesis Main Idea Matching',
    explanation: {
      passageDeconstruction: `Contrast: single-origin theory (West Africa only) vs complex synthesis (West African rhythms + European harmonies + French quadrilles + Caribbean habanera rhythms).`,
      correctReasoning: `Option A accurately states the central thesis of multi-cultural synthesis.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'New Orleans jazz emerged from a blend of West African...', trapType: 'Correct Main Idea', whyIncorrect: 'Correctly summarizes the hybrid synthesis thesis.' },
        { optionIndex: 1, optionText: 'West African rhythmic traditions were completely excluded...', trapType: 'Direct Contradiction', whyIncorrect: 'Text explicitly highlights West African syncopation as a key ingredient.' },
        { optionIndex: 2, optionText: 'French quadrille dance music was the single most important...', trapType: 'Single Factor Trap', whyIncorrect: 'Text presents multiple equal contributing traditions.' },
        { optionIndex: 3, optionText: 'European harmonic progressions developed independently...', trapType: 'Irrelevant Fact', whyIncorrect: 'European music history before jazz is not discussed.' }
      ]
    }
  },
  {
    id: 't2-ex-32',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Easy/Medium Module',
    passage: `In avian biology, homing pigeons navigate back to their lofts over hundreds of miles by utilizing a dual-sensory guidance system. For long-distance orientation, they rely on an internal magnetic compass sensitive to Earth\'s geomagnetic field; once within local territory, they switch to visual landmarks, such as highways, rivers, and prominent buildings.`,
    questionText: `According to the text, how do homing pigeons navigate when close to their destination?`,
    options: [
      'They rely on visual landmarks such as rivers and buildings.',
      'They track smell gradients carried by local wind currents.',
      'They emit ultrasonic clicks that bounce off terrain features.',
      'They follow celestial constellations across the night sky.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Direct Textual Detail Retrieval',
    explanation: {
      passageDeconstruction: `Target detail: How do homing pigeons navigate when CLOSE to their destination ("within local territory")? Text states: "once within local territory, they switch to visual landmarks, such as highways, rivers, and prominent buildings".`,
      correctReasoning: `Option A directly matches the local navigation mechanism described.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'They rely on visual landmarks such as rivers and buildings.', trapType: 'Direct Textual Match', whyIncorrect: 'Correct. Directly stated in text for local territory.' },
        { optionIndex: 1, optionText: 'They track smell gradients...', trapType: 'Unmentioned Mechanism', whyIncorrect: 'Olfactory navigation is not mentioned.' },
        { optionIndex: 2, optionText: 'They emit ultrasonic clicks...', trapType: 'Echolocation Swap Trap', whyIncorrect: 'Pigeons do not use echolocation.' },
        { optionIndex: 3, optionText: 'They follow celestial constellations...', trapType: 'Star Navigation Swap Trap', whyIncorrect: 'Constellations are not mentioned.' }
      ]
    }
  },
  {
    id: 't2-ex-33',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Hard Module',
    passage: `Although nineteenth-century economic historian Karl Marx argued that industrial automation would inevitably lead to the total impoverishment of the working class, late twentieth-century empirical data showed a more complex outcome. While automation eliminated traditional manufacturing jobs, it simultaneously increased overall economic productivity, driving up real wages and expanding employment in service and technology sectors.`,
    questionText: `Which choice best states the main idea of the text?`,
    options: [
      'Industrial automation led to productivity gains and new employment sectors, countering Marx\'s prediction of total working-class impoverishment.',
      'Marx\'s economic theories were fully validated by late twentieth-century manufacturing trends.',
      'Automation completely eradicated working-class poverty in Western industrial nations.',
      'Service sector employment declined rapidly following the introduction of automated machinery.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Main Idea Synthesis',
    explanation: {
      passageDeconstruction: `Contrast: Marx\'s prediction (automation causes total working-class impoverishment) vs late 20th-century reality (increased productivity, higher real wages, expansion of service/tech jobs).`,
      correctReasoning: `Option A accurately synthesizes the main thesis refuting Marx\'s absolute prediction.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'Industrial automation led to productivity gains...', trapType: 'Correct Main Idea', whyIncorrect: 'Correct synthesis of historical outcome vs prediction.' },
        { optionIndex: 1, optionText: 'Marx\'s economic theories were fully validated...', trapType: 'Direct Contradiction', whyIncorrect: 'Text states empirical data showed a outcome countering Marx.' },
        { optionIndex: 2, optionText: 'Automation completely eradicated working-class poverty...', trapType: 'Extreme Absolute Trap', whyIncorrect: 'Text states it increased real wages and tech jobs, not that poverty was "completely eradicated".' },
        { optionIndex: 3, optionText: 'Service sector employment declined rapidly...', trapType: 'Direct Contradiction', whyIncorrect: 'Text explicitly states service sector employment expanded.' }
      ]
    }
  },
  {
    id: 't2-ex-34',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Easy/Medium Module',
    passage: `In marine conservation, mangrove forests serve as critical nursery habitats for commercial fish species. The dense tangle of prop roots traps sediment and attenuates wave energy, creating calm, nutrient-rich shallow waters where juvenile fish can feed safely away from large pelagic predators.`,
    questionText: `According to the text, why are mangrove prop roots beneficial to young fish?`,
    options: [
      'They reduce wave energy and create calm waters protected from pelagic predators.',
      'They secrete natural antibiotics that prevent bacterial fish infections.',
      'They absorb toxic chemical runoff from nearby agricultural developments.',
      'They produce oxygen gas that dissolves directly into shallow tide pools.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Direct Fact Retrieval',
    explanation: {
      passageDeconstruction: `Direct question: Why do prop roots benefit juvenile fish? Text states: "traps sediment and attenuates wave energy, creating calm, nutrient-rich shallow waters where juvenile fish can feed safely away from large pelagic predators".`,
      correctReasoning: `Option A accurately captures reducing wave energy and protecting young fish from predators.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'They reduce wave energy and create calm waters...', trapType: 'Direct Textual Match', whyIncorrect: 'Correct. Directly stated in text.' },
        { optionIndex: 1, optionText: 'They secrete natural antibiotics...', trapType: 'Unmentioned Secretion', whyIncorrect: 'Antibiotics are not mentioned.' },
        { optionIndex: 2, optionText: 'They absorb toxic chemical runoff...', trapType: 'Unmentioned Runoff', whyIncorrect: 'Toxic runoff absorption is not mentioned.' },
        { optionIndex: 3, optionText: 'They produce oxygen gas...', trapType: 'Fabricated Function', whyIncorrect: 'Oxygen production in tide pools is not described as the nursery benefit.' }
      ]
    }
  },
  {
    id: 't2-ex-35',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Hard Module',
    passage: `In twentieth-century linguistic theory, Noam Chomsky proposed the concept of Universal Grammar, asserting that human children possess an innate biological capacity for language acquisition. Chomsky argued that the rapid speed and uniform accuracy with which infants master complex grammatical rules—despite receiving limited and fragmented speech input—cannot be explained by general behavioral learning alone.`,
    questionText: `Which choice best states the main idea of the passage?`,
    options: [
      'Chomsky argued that children master language rapidly due to an innate biological capacity rather than mere environmental imitation.',
      'Behavioral learning models completely account for how children acquire native language syntax.',
      'Infants require formal grammar instruction to develop coherent speech patterns.',
      'Universal Grammar theories have been disproved by recent childhood speech recordings.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Main Thesis Extraction',
    explanation: {
      passageDeconstruction: `Thesis: Universal Grammar posits an innate biological capacity for language because speed and mastery exceed what behavioral learning from fragmented input could explain.`,
      correctReasoning: `Option A accurately states Chomsky\'s core argument.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'Chomsky argued that children master language rapidly...', trapType: 'Correct Main Idea', whyIncorrect: 'Correctly captures Universal Grammar thesis.' },
        { optionIndex: 1, optionText: 'Behavioral learning models completely account for how...', trapType: 'Direct Contradiction', whyIncorrect: 'Chomsky argued behavioral models were insufficient.' },
        { optionIndex: 2, optionText: 'Infants require formal grammar instruction...', trapType: 'Direct Contradiction', whyIncorrect: 'Text notes infants master grammar without formal instruction despite fragmented input.' },
        { optionIndex: 3, optionText: 'Universal Grammar theories have been disproved...', trapType: 'Unmentioned Refutation', whyIncorrect: 'Disproving the theory is not mentioned in the text.' }
      ]
    }
  },
  {
    id: 't2-ex-36',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Easy/Medium Module',
    passage: `In solar astronomy, coronal mass ejections (CMEs) are massive bursts of solar wind and magnetic fields released from the Sun\'s corona. When a CME collides with Earth\'s magnetosphere, it induces geomagnetic storms that can disrupt satellite communications, disable GPS navigation networks, and overload high-voltage electrical power grids.`,
    questionText: `According to the text, what impact can geomagnetic storms caused by CMEs have on technology?`,
    options: [
      'Disrupting satellite communications, GPS networks, and power grids.',
      'Increasing atmospheric ozone concentration over polar regions.',
      'Permanent destruction of deep-sea fiber optic internet cables.',
      'Accelerating the decay rate of terrestrial nuclear power fuel.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Direct Textual Detail Retrieval',
    explanation: {
      passageDeconstruction: `Direct question: What impact do geomagnetic storms have on technology? Text states: "disrupt satellite communications, disable GPS navigation networks, and overload high-voltage electrical power grids".`,
      correctReasoning: `Option A accurately lists the three technological impacts stated in the passage.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'Disrupting satellite communications, GPS networks...', trapType: 'Direct Textual Match', whyIncorrect: 'Correct. Directly stated in text.' },
        { optionIndex: 1, optionText: 'Increasing atmospheric ozone concentration...', trapType: 'Unmentioned Impact', whyIncorrect: 'Ozone concentration is not mentioned.' },
        { optionIndex: 2, optionText: 'Permanent destruction of deep-sea fiber optic internet cables...', trapType: 'Extreme Fabricated Impact', whyIncorrect: 'Deep-sea fiber optic cables are not mentioned.' },
        { optionIndex: 3, optionText: 'Accelerating the decay rate of terrestrial nuclear power fuel...', trapType: 'Scientific Fallacy', whyIncorrect: 'Nuclear decay rates are unaffected by geomagnetic storms.' }
      ]
    }
  },
  {
    id: 't2-ex-37',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Hard Module',
    passage: `While eighteenth-century literary critics dismissed Mary Shelley\'s *Frankenstein* as a sensationalist gothic tale, modern scholars recognize it as a foundational work of science fiction that critiques scientific overreach. Shelley portrays Victor Frankenstein not as a heroic seeker of knowledge, but as an irresponsible creator whose abandonment of his creature leads to tragedy, raising enduring ethical questions about technological hubris.`,
    questionText: `Which choice best states the main idea of the text?`,
    options: [
      'Modern scholars view *Frankenstein* as a foundational critique of irresponsible scientific hubris rather than a simple gothic thriller.',
      'Shelley intended Victor Frankenstein to be celebrated as an unblemished hero of Enlightenment science.',
      'Eighteenth-century critics praised Shelley for her accurate predictions of future medical technology.',
      '*Frankenstein* was the first novel to advocate for total prohibition of biological research.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Main Idea Synthesis',
    explanation: {
      passageDeconstruction: `Contrast: old view (sensationalist gothic tale) vs modern view (foundational sci-fi critiquing scientific overreach and irresponsible creation).`,
      correctReasoning: `Option A accurately summarizes the shift in scholarly perspective and the novel\'s core thematic critique.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'Modern scholars view *Frankenstein* as a foundational critique...', trapType: 'Correct Main Idea', whyIncorrect: 'Correct. Accurately synthesizes the passage\'s thesis.' },
        { optionIndex: 1, optionText: 'Shelley intended Victor Frankenstein to be celebrated as an unblemished hero...', trapType: 'Direct Contradiction', whyIncorrect: 'Text states Victor is portrayed as an "irresponsible creator", not an unblemished hero.' },
        { optionIndex: 2, optionText: 'Eighteenth-century critics praised Shelley for her accurate predictions...', trapType: 'Direct Contradiction', whyIncorrect: 'Text states 18th-century critics dismissed the novel as sensationalist.' },
        { optionIndex: 3, optionText: 'Frankenstein was the first novel to advocate for total prohibition...', trapType: 'Extreme Policy Trap', whyIncorrect: 'Text mentions ethical questions about hubris, not a call for total prohibition of research.' }
      ]
    }
  },
  {
    id: 't2-ex-38',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Easy/Medium Module',
    passage: `In marine geology, abyssal plains cover more than 50% of Earth\'s ocean floor at depths between 3,000 and 6,000 meters. These vast, flat regions are formed by thick layers of pelagic sediment—composed of microscopic plankton shells and windblown continental dust—accumulating slowly over millions of years to bury underlying basaltic ocean crust.`,
    questionText: `According to the text, how are abyssal plains formed?`,
    options: [
      'By pelagic sediment accumulating slowly over millions of years to cover ocean crust.',
      'By rapid volcanic lava flows spreading outward from mid-ocean ridges.',
      'By tectonic plate collisions pushing continental shelf rock downward.',
      'By iceberg scouring scraping away underwater mountain ranges.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Direct Detail Retrieval',
    explanation: {
      passageDeconstruction: `Direct question: How are abyssal plains formed? Text states: "formed by thick layers of pelagic sediment... accumulating slowly over millions of years to bury underlying basaltic ocean crust".`,
      correctReasoning: `Option A directly states the sediment accumulation mechanism given in the passage.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'By pelagic sediment accumulating slowly over millions of years...', trapType: 'Direct Textual Match', whyIncorrect: 'Correct. Directly stated in text.' },
        { optionIndex: 1, optionText: 'By rapid volcanic lava flows spreading outward...', trapType: 'Geological Mechanism Swap', whyIncorrect: 'Rapid lava flows are not mentioned as the plain-forming mechanism.' },
        { optionIndex: 2, optionText: 'By tectonic plate collisions pushing shelf rock downward...', trapType: 'Geological Mechanism Swap', whyIncorrect: 'Tectonic collisions are not described.' },
        { optionIndex: 3, optionText: 'By iceberg scouring scraping away underwater mountain ranges...', trapType: 'Fabricated Mechanism', whyIncorrect: 'Iceberg scouring is not mentioned.' }
      ]
    }
  },
  {
    id: 't2-ex-39',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Hard Module',
    passage: `Although mid-twentieth-century urban planners promoted extensive highway construction as the definitive solution to city traffic, contemporary urban designers highlight its counterproductive effects. Building highways through urban centers physically severed historic neighborhoods, displaced residents, and encouraged vehicle dependency—ultimately worsening traffic through induced demand rather than resolving congestion.`,
    questionText: `Which choice best states the main idea of the passage?`,
    options: [
      'Urban highway expansion damaged communities and failed to solve traffic congestion.',
      'Mid-twentieth-century urban planners successfully eliminated traffic in major cities.',
      'Contemporary designers advocate replacing public transit lines with wider expressways.',
      'Highway construction through cities was motivated purely by environmental protection concerns.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Main Idea Synthesis',
    explanation: {
      passageDeconstruction: `Contrast: mid-20th century promise (highways solve traffic) vs modern reality (damaged neighborhoods, displaced residents, worsened traffic via induced demand).`,
      correctReasoning: `Option A accurately synthesizes both the social damage and traffic failure of urban highways.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'Urban highway expansion damaged communities and failed to solve...', trapType: 'Correct Main Idea', whyIncorrect: 'Correctly captures both negative consequences.' },
        { optionIndex: 1, optionText: 'Mid-twentieth-century urban planners successfully eliminated traffic...', trapType: 'Direct Contradiction', whyIncorrect: 'Text states highway construction worsened traffic.' },
        { optionIndex: 2, optionText: 'Contemporary designers advocate replacing public transit lines...', trapType: 'Direct Contradiction', whyIncorrect: 'Contemporary designers critique highway reliance, not transit.' },
        { optionIndex: 3, optionText: 'Highway construction through cities was motivated purely by environmental...', trapType: 'Fabricated Motivation', whyIncorrect: 'Environmental concerns are not mentioned as the original motivation.' }
      ]
    }
  },
  {
    id: 't2-ex-40',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Easy/Medium Module',
    passage: `In biochemistry, enzymes function as biological catalysts by lowering the activation energy required for chemical reactions. By binding specific substrate molecules at their active sites, enzymes stabilize reaction transition states, enabling biochemical processes to occur millions of times faster than they would spontaneously at body temperature.`,
    questionText: `According to the text, how do enzymes speed up chemical reactions?`,
    options: [
      'By lowering the activation energy required for reactions to occur.',
      'By raising body temperature within local cellular compartments.',
      'By permanently changing the chemical structure of substrate molecules.',
      'By consuming cellular ATP to produce kinetic friction.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Direct Fact Verification',
    explanation: {
      passageDeconstruction: `Direct question: How do enzymes speed up reactions? Text explicitly states: "function as biological catalysts by lowering the activation energy required for chemical reactions".`,
      correctReasoning: `Option A directly mirrors the activation energy mechanism stated in the text.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'By lowering the activation energy required for reactions...', trapType: 'Direct Textual Match', whyIncorrect: 'Correct. Directly stated in text.' },
        { optionIndex: 1, optionText: 'By raising body temperature within local cellular compartments...', trapType: 'Direct Contradiction', whyIncorrect: 'Text states reactions happen faster "at body temperature", not by raising temperature.' },
        { optionIndex: 2, optionText: 'By permanently changing the chemical structure...', trapType: 'Biochemical Fallacy', whyIncorrect: 'Enzymes stabilize transition states without being permanently altered themselves.' },
        { optionIndex: 3, optionText: 'By consuming cellular ATP to produce kinetic friction...', trapType: 'Fabricated Mechanism', whyIncorrect: 'Kinetic friction is not mentioned.' }
      ]
    }
  },
  {
    id: 't2-ex-41',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Hard Module',
    passage: `While early nineteenth-century historians credited the abolition of the British transatlantic slave trade in 1807 primarily to parliamentary evangelical reformers like William Wilberforce, modern historians emphasize the critical role of enslaved resistance. Slave uprisings in the West Indies—most notably the Haitian Revolution—shattered the perceived stability of plantation economies, making the slave trade financially precarious and militarily unviable.`,
    questionText: `Which choice best states the main idea of the passage?`,
    options: [
      'Modern historians highlight enslaved resistance and economic instability as key drivers in ending the British slave trade.',
      'William Wilberforce was the sole historical figure responsible for dismantling West Indian plantations.',
      'The Haitian Revolution had no measurable impact on British colonial policy.',
      'British parliamentary reformers opposed abolition due to fear of financial losses in West Indian trade.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Main Idea Synthesis',
    explanation: {
      passageDeconstruction: `Contrast: old historical view (Wilberforce and parliamentary reformers did it all) vs modern view (enslaved uprisings like the Haitian Revolution made plantation slavery financially and militarily unsustainable).`,
      correctReasoning: `Option A accurately states the modern historical synthesis.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'Modern historians highlight enslaved resistance and economic...', trapType: 'Correct Main Idea', whyIncorrect: 'Correct. Accurately synthesizes modern historical consensus.' },
        { optionIndex: 1, optionText: 'William Wilberforce was the sole historical figure responsible...', trapType: 'Direct Contradiction', whyIncorrect: 'Text rejects attributing abolition solely to Wilberforce.' },
        { optionIndex: 2, optionText: 'The Haitian Revolution had no measurable impact on British...', trapType: 'Direct Contradiction', whyIncorrect: 'Text highlights the Haitian Revolution as shattering plantation stability.' },
        { optionIndex: 3, optionText: 'British parliamentary reformers opposed abolition...', trapType: 'Role Reversal', whyIncorrect: 'Wilberforce and reformers supported abolition, not opposed it.' }
      ]
    }
  },
  {
    id: 't2-ex-42',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Easy/Medium Module',
    passage: `In botanical ecology, mycorrhizal fungi form symbiotic networks with plant roots, trading soil minerals for plant sugars. Fungal hyphae extend far beyond root zones to absorb phosphorus and nitrogen, which they transfer to plants in exchange for photosynthetic carbohydrates, enhancing plant growth in nutrient-poor soils.`,
    questionText: `According to the text, what do mycorrhizal fungi receive from plants in exchange for soil minerals?`,
    options: [
      'Photosynthetic carbohydrates.',
      'Phosphorus and nitrogen compounds.',
      'Groundwater filtered through leaf tissue.',
      'Protective waxy coatings on hyphae.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Direct Detail Retrieval',
    explanation: {
      passageDeconstruction: `Direct question: What do fungi receive from plants? Text explicitly says: "trading soil minerals for plant sugars... transfer to plants in exchange for photosynthetic carbohydrates".`,
      correctReasoning: `Option A directly states photosynthetic carbohydrates (sugars).`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'Photosynthetic carbohydrates.', trapType: 'Direct Textual Match', whyIncorrect: 'Correct. Directly stated in text.' },
        { optionIndex: 1, optionText: 'Phosphorus and nitrogen compounds.', trapType: 'Role Swap Trap', whyIncorrect: 'Phosphorus and nitrogen are what fungi GIVE to plants, not receive.' },
        { optionIndex: 2, optionText: 'Groundwater filtered through leaf tissue.', trapType: 'Unmentioned Exchange', whyIncorrect: 'Filtered groundwater is not mentioned.' },
        { optionIndex: 3, optionText: 'Protective waxy coatings on hyphae.', trapType: 'Unmentioned Exchange', whyIncorrect: 'Waxy coatings are not mentioned.' }
      ]
    }
  },
  {
    id: 't2-ex-43',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Hard Module',
    passage: `Although twentieth-century literary criticism often categorized folklore as static oral tradition preserved unchanged across generations, contemporary folklorists emphasize its fluid, performative nature. Each retelling of a traditional folktale adapts the narrative to contemporary audience concerns, political contexts, and local community values, demonstrating that folklore is a living, evolving form of cultural expression.`,
    questionText: `Which choice best states the main idea of the passage?`,
    options: [
      'Folklore is a dynamic, evolving performance that adapts to contemporary contexts rather than a fixed historical artifact.',
      'Twentieth-century literary critics accurately documented all variations of traditional folktales.',
      'Traditional folktales lose their cultural value whenever storytellers alter original plot elements.',
      'Oral storytelling traditions have completely vanished in modern industrial societies.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Main Idea Synthesis',
    explanation: {
      passageDeconstruction: `Contrast: old view (static oral tradition unchanged across generations) vs modern view (fluid, performative, living, evolving cultural expression adapting to audience concerns).`,
      correctReasoning: `Option A accurately summarizes the modern folklorist perspective.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'Folklore is a dynamic, evolving performance that adapts...', trapType: 'Correct Main Idea', whyIncorrect: 'Correctly captures the central thesis.' },
        { optionIndex: 1, optionText: 'Twentieth-century literary critics accurately documented all...', trapType: 'Direct Contradiction', whyIncorrect: 'Text states early critics wrongly viewed folklore as static.' },
        { optionIndex: 2, optionText: 'Traditional folktales lose their cultural value whenever...', trapType: 'Direct Contradiction', whyIncorrect: 'Text argues retelling and adapting keeps folklore alive and meaningful.' },
        { optionIndex: 3, optionText: 'Oral storytelling traditions have completely vanished...', trapType: 'Extrapolated Absolute', whyIncorrect: 'Extinction of oral storytelling is not mentioned.' }
      ]
    }
  },
  {
    id: 't2-ex-44',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Easy/Medium Module',
    passage: `In renewable energy engineering, offshore wind turbines generate up to 50% more electricity than onshore turbines of equivalent size. Higher and more consistent wind speeds over open ocean waters eliminate land terrain friction, allowing larger turbine blades to spin continuously and produce higher electrical yields.`,
    questionText: `According to the text, why do offshore wind turbines produce more electricity than onshore turbines?`,
    options: [
      'Ocean winds are stronger and more consistent due to a lack of land terrain friction.',
      'Saltwater currents spin turbine bases underwater to generate auxiliary power.',
      'Offshore turbines utilize solar panels mounted on blade tips.',
      'Ocean water cools electrical generators to prevent thermal energy loss.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Direct Cause Detail Matching',
    explanation: {
      passageDeconstruction: `Direct question: Why do offshore turbines produce more electricity? Text states: "Higher and more consistent wind speeds over open ocean waters eliminate land terrain friction, allowing larger turbine blades to spin continuously".`,
      correctReasoning: `Option A accurately states the wind speed and lack of terrain friction cause.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'Ocean winds are stronger and more consistent due to...', trapType: 'Direct Textual Match', whyIncorrect: 'Correct. Directly stated in text.' },
        { optionIndex: 1, optionText: 'Saltwater currents spin turbine bases underwater...', trapType: 'Fabricated Mechanism', whyIncorrect: 'Underwater current spinning is not mentioned.' },
        { optionIndex: 2, optionText: 'Offshore turbines utilize solar panels mounted...', trapType: 'Fabricated Technology', whyIncorrect: 'Solar panels on blades are not mentioned.' },
        { optionIndex: 3, optionText: 'Ocean water cools electrical generators...', trapType: 'Fabricated Mechanism', whyIncorrect: 'Water cooling of generators is not mentioned.' }
      ]
    }
  },
  {
    id: 't2-ex-45',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Hard Module',
    passage: `While early twentieth-century psychologists viewed forgetting solely as a passive decay of memory traces over time, modern cognitive neuroscientists recognize it as an active, adaptive brain process. Forgetting irrelevant or outdated information reduces cognitive interference, allowing the brain to retrieve goal-relevant memories more efficiently and make flexible decisions in novel environments.`,
    questionText: `Which choice best states the main idea of the passage?`,
    options: [
      'Forgetting is an active, adaptive process that improves memory efficiency and decision-making.',
      'Memory traces decay passively in fixed linear patterns regardless of mental activity.',
      'Retaining all past sensory experiences is essential for effective cognitive functioning.',
      'Neuroscientists recommend memory-suppression drugs to accelerate decision-making.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Main Idea Synthesis',
    explanation: {
      passageDeconstruction: `Contrast: old view (passive decay) vs modern view (active, adaptive process that reduces cognitive interference and improves decision-making).`,
      correctReasoning: `Option A summarizes the modern neuroscientific view accurately.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'Forgetting is an active, adaptive process that improves memory...', trapType: 'Correct Main Idea', whyIncorrect: 'Correctly captures modern neuroscientific consensus.' },
        { optionIndex: 1, optionText: 'Memory traces decay passively in fixed linear patterns...', trapType: 'Direct Contradiction', whyIncorrect: 'Text states passive decay was an outdated view.' },
        { optionIndex: 2, optionText: 'Retaining all past sensory experiences is essential...', trapType: 'Direct Contradiction', whyIncorrect: 'Text states forgetting irrelevant information is what enables efficient cognition.' },
        { optionIndex: 3, optionText: 'Neuroscientists recommend memory-suppression drugs...', trapType: 'Fabricated Policy Trap', whyIncorrect: 'Memory-suppression drugs are not mentioned.' }
      ]
    }
  },
  {
    id: 't2-ex-46',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Easy/Medium Module',
    passage: `In entomology, honeybee colonies regulate hive temperature around 35°C during brood rearing. When ambient temperatures rise, worker bees collect water droplets and spread them across the wax honeycomb, fanning their wings rapidly to create evaporative cooling that lowers interior hive temperatures.`,
    questionText: `According to the text, how do worker honeybees cool the hive during hot weather?`,
    options: [
      'They spread water droplets on the honeycomb and fan their wings to create evaporative cooling.',
      'They seal hive entrances with propolis to block warm outside air.',
      'They consume royal jelly to lower their individual body temperatures.',
      'They evacuate the brood chamber and cluster on exterior tree branches.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Direct Detail Retrieval',
    explanation: {
      passageDeconstruction: `Direct question: How do bees cool the hive? Text explicitly states: "worker bees collect water droplets and spread them across the wax honeycomb, fanning their wings rapidly to create evaporative cooling".`,
      correctReasoning: `Option A directly states the water droplet spreading and wing fanning behavior.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'They spread water droplets on the honeycomb and fan their wings...', trapType: 'Direct Textual Match', whyIncorrect: 'Correct. Directly stated in text.' },
        { optionIndex: 1, optionText: 'They seal hive entrances with propolis...', trapType: 'Unmentioned Behavior', whyIncorrect: 'Propolis sealing is not mentioned.' },
        { optionIndex: 2, optionText: 'They consume royal jelly...', trapType: 'Royal Jelly Swap Trap', whyIncorrect: 'Royal jelly is for queen rearing, not cooling.' },
        { optionIndex: 3, optionText: 'They evacuate the brood chamber...', trapType: 'Direct Contradiction', whyIncorrect: 'Bees cool the hive specifically to protect the brood chamber.' }
      ]
    }
  },
  {
    id: 't2-ex-47',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Hard Module',
    passage: `Although nineteenth-century art critics dismissed impressionist paintings for their visible brushstrokes and unblended colors, modern art historians recognize these techniques as a deliberate revolution in visual perception. By capturing fleeting conditions of light and atmosphere rather than static studio forms, Impressionist artists reflected the accelerating pace and sensory dynamism of late nineteenth-century urban life.`,
    questionText: `Which choice best states the main idea of the passage?`,
    options: [
      'Impressionist painting techniques deliberately reflected the dynamic light and fast pace of modern urban life.',
      'Nineteenth-century critics praised impressionists for preserving traditional studio painting standards.',
      'Impressionists painted exclusively indoors to control light conditions on their canvases.',
      'Visible brushstrokes were accidental flaws resulting from poor paint quality in the 1870s.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Main Idea Synthesis',
    explanation: {
      passageDeconstruction: `Contrast: old critics (dismissed visible brushstrokes) vs modern historians (recognized techniques as deliberate revolution capturing fleeting light and urban dynamism).`,
      correctReasoning: `Option A accurately states the modern historical main idea.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'Impressionist painting techniques deliberately reflected...', trapType: 'Correct Main Idea', whyIncorrect: 'Correct synthesis of historical artistic intent.' },
        { optionIndex: 1, optionText: 'Nineteenth-century critics praised impressionists...', trapType: 'Direct Contradiction', whyIncorrect: 'Text states early critics dismissed impressionists.' },
        { optionIndex: 2, optionText: 'Impressionists painted exclusively indoors...', trapType: 'Direct Contradiction', whyIncorrect: 'Text states they captured fleeting outdoor light rather than static studio forms.' },
        { optionIndex: 3, optionText: 'Visible brushstrokes were accidental flaws resulting from poor paint...', trapType: 'Direct Contradiction', whyIncorrect: 'Text states brushstrokes were a deliberate technique.' }
      ]
    }
  },
  {
    id: 't2-ex-48',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Easy/Medium Module',
    passage: `In marine biology, sea turtles undertake multi-thousand-mile ocean migrations to return to the exact beaches where they hatched—a phenomenon known as natal homing. Researchers discovered that hatchlings imprint on the unique geomagnetic signature of their birth beach, using Earth\'s magnetic field intensity and inclination angle to navigate back decades later as nesting adults.`,
    questionText: `According to the text, how do adult sea turtles locate their birth beaches decades after hatching?`,
    options: [
      'They navigate using the unique geomagnetic signature imprinted during hatching.',
      'They follow chemical scent plumes released by coastal mangrove trees.',
      'They track underwater acoustic signals from adult turtle colonies.',
      'They rely on ocean surface current patterns driven by seasonal trade winds.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Direct Detail Retrieval',
    explanation: {
      passageDeconstruction: `Direct question: How do sea turtles navigate back to natal beaches? Text explicitly states: "hatchlings imprint on the unique geomagnetic signature of their birth beach, using Earth\'s magnetic field intensity and inclination angle to navigate back".`,
      correctReasoning: `Option A directly states geomagnetic signature navigation.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'They navigate using the unique geomagnetic signature...', trapType: 'Direct Textual Match', whyIncorrect: 'Correct. Directly stated in text.' },
        { optionIndex: 1, optionText: 'They follow chemical scent plumes...', trapType: 'Unmentioned Mechanism', whyIncorrect: 'Chemical scent plumes are not mentioned.' },
        { optionIndex: 2, optionText: 'They track underwater acoustic signals...', trapType: 'Unmentioned Mechanism', whyIncorrect: 'Acoustic signals are not mentioned.' },
        { optionIndex: 3, optionText: 'They rely on ocean surface current patterns...', trapType: 'Unmentioned Mechanism', whyIncorrect: 'Ocean surface currents are not described as the navigation mechanism.' }
      ]
    }
  },
  {
    id: 't2-ex-49',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Hard Module',
    passage: `While early historians credited the construction of the Great Wall of China to a single unified defensive strategy, modern archaeological surveys reveal a much more piecemeal reality. The wall consists of separate fortification networks built, abandoned, and rebuilt across different dynasties over two millennia, reflecting shifting local border alliances and political rivalries rather than a single master blueprint.`,
    questionText: `Which choice best states the main idea of the passage?`,
    options: [
      'The Great Wall was built incrementally across multiple dynasties, reflecting changing border dynamics rather than a single unified plan.',
      'Archaeological evidence proves the Great Wall was constructed entirely during a single emperor\'s reign.',
      'The Great Wall failed completely as a defensive barrier due to poor masonry construction.',
      'Early historians accurately documented the construction records of all Chinese dynasties.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Main Idea Synthesis',
    explanation: {
      passageDeconstruction: `Contrast: old myth (single unified defensive strategy) vs archaeological reality (piecemeal networks built, abandoned, and rebuilt across 2,000 years reflecting local alliances).`,
      correctReasoning: `Option A accurately states the piecemeal, multi-dynasty construction reality.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'The Great Wall was built incrementally across multiple dynasties...', trapType: 'Correct Main Idea', whyIncorrect: 'Correctly captures the archaeological finding.' },
        { optionIndex: 1, optionText: 'Archaeological evidence proves the Great Wall was constructed entirely during...', trapType: 'Direct Contradiction', whyIncorrect: 'Text states it was built across different dynasties over two millennia.' },
        { optionIndex: 2, optionText: 'The Great Wall failed completely as a defensive barrier due to poor masonry...', trapType: 'Unmentioned Quality Claim', whyIncorrect: 'Poor masonry is not discussed.' },
        { optionIndex: 3, optionText: 'Early historians accurately documented the construction records...', trapType: 'Direct Contradiction', whyIncorrect: 'Text shows early historians held an inaccurate view.' }
      ]
    }
  },
  {
    id: 't2-ex-50',
    moduleNumber: 1,
    subskill: 'Central Ideas & Details',
    difficulty: 'Easy/Medium Module',
    passage: `In plant biochemistry, anthocyanins are water-soluble pigments that give autumn leaves their red and purple hues. While chlorophyll breaks down in cooler weather revealing yellow carotenoids, plants actively synthesize new anthocyanin molecules in autumn leaves to protect photosynthetic cells from light damage while nutrients are remobilized into tree trunks.`,
    questionText: `According to the text, why do plants synthesize anthocyanins in autumn leaves?`,
    options: [
      'To protect photosynthetic cells from light damage during nutrient recovery.',
      'To attract pollinating insects before winter frost arrives.',
      'To absorb excess soil moisture following heavy autumn rainfalls.',
      'To accelerate leaf drop before winter storms damage branches.'
    ],
    correctAnswer: 0,
    nextGenTechnique: 'Direct Detail Verification',
    explanation: {
      passageDeconstruction: `Direct question: Why do plants synthesize anthocyanins in autumn? Text states: "actively synthesize new anthocyanin molecules in autumn leaves to protect photosynthetic cells from light damage while nutrients are remobilized into tree trunks".`,
      correctReasoning: `Option A directly mirrors the light protection function described in the text.`,
      distractorAnalysis: [
        { optionIndex: 0, optionText: 'To protect photosynthetic cells from light damage...', trapType: 'Direct Textual Match', whyIncorrect: 'Correct. Directly stated in text.' },
        { optionIndex: 1, optionText: 'To attract pollinating insects...', trapType: 'Autumn Insect Trap', whyIncorrect: 'Pollinating insects in autumn are not mentioned.' },
        { optionIndex: 2, optionText: 'To absorb excess soil moisture...', trapType: 'Fabricated Mechanism', whyIncorrect: 'Soil moisture absorption is not mentioned.' },
        { optionIndex: 3, optionText: 'To accelerate leaf drop...', trapType: 'Opposite Action', whyIncorrect: 'Anthocyanins protect leaves while nutrients are recovered, not accelerate drop.' }
      ]
    }
  }
];
